---
- name: Run script to Delete the Duplicate Datasets
  hosts:  catalog-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - { role: dup-dataset-removal, tags: [provision, misc] }
